import 'package:flutter/material.dart';
import 'package:islami_app/core/constants/app_assets.dart';
import 'package:islami_app/core/theme/color_palette.dart';
import 'package:islami_app/models/sura_data_model.dart';
import 'package:islami_app/modules/layout/pages/quran/widgets/quran_card_widgett.dart';
import 'package:islami_app/modules/layout/pages/quran/widgets/recently_card_widget.dart';

class QuranView extends StatefulWidget {
  const QuranView({super.key});

  @override
  State<QuranView> createState() => _QuranViewState();
}

class _QuranViewState extends State<QuranView> {
  List<SuraDataModel> allSuras = [
    SuraDataModel(suraNameAR: "الفاتحه",
        suraNameEN: "Al-Fatiha",
        suraNumber: 1,
        suraAyatCount: 7),
    SuraDataModel(suraNameAR: "البقرة",
        suraNameEN: "Al-Baqarah",
        suraNumber: 2,
        suraAyatCount: 286),
    SuraDataModel(suraNameAR: "آل عمران",
        suraNameEN: "Aal-E-Imran",
        suraNumber: 3,
        suraAyatCount: 200),
    SuraDataModel(suraNameAR: "النساء",
        suraNameEN: "An-Nisa'",
        suraNumber: 4,
        suraAyatCount: 176),
    SuraDataModel(suraNameAR: "المائدة",
        suraNameEN: "Al-Ma'idah",
        suraNumber: 5,
        suraAyatCount: 120),
    SuraDataModel(suraNameAR: "الأنعام",
        suraNameEN: "Al-An'am",
        suraNumber: 6,
        suraAyatCount: 165),
    SuraDataModel(suraNameAR: "الأعراف",
        suraNameEN: "Al-A'raf",
        suraNumber: 7,
        suraAyatCount: 206),
    SuraDataModel(suraNameAR: "الأنفال",
        suraNameEN: "Al-Anfal",
        suraNumber: 8,
        suraAyatCount: 75),
    SuraDataModel(suraNameAR: "التوبة",
        suraNameEN: "At-Tawbah",
        suraNumber: 9,
        suraAyatCount: 129),
    SuraDataModel(suraNameAR: "يونس",
        suraNameEN: "Yunus",
        suraNumber: 10,
        suraAyatCount: 109),
    SuraDataModel(suraNameAR: "هود",
        suraNameEN: "Hud",
        suraNumber: 11,
        suraAyatCount: 123),
    SuraDataModel(suraNameAR: "يوسف",
        suraNameEN: "Yusuf",
        suraNumber: 12,
        suraAyatCount: 111),
    SuraDataModel(suraNameAR: "الرعد",
        suraNameEN: "Ar-Ra'd",
        suraNumber: 13,
        suraAyatCount: 43),
    SuraDataModel(suraNameAR: "إبراهيم",
        suraNameEN: "Ibrahim",
        suraNumber: 14,
        suraAyatCount: 52),
    SuraDataModel(suraNameAR: "الحجر",
        suraNameEN: "Al-Hijr",
        suraNumber: 15,
        suraAyatCount: 99),
    SuraDataModel(suraNameAR: "النحل",
        suraNameEN: "An-Nahl",
        suraNumber: 16,
        suraAyatCount: 128),
    SuraDataModel(suraNameAR: "الإسراء",
        suraNameEN: "Al-Isra",
        suraNumber: 17,
        suraAyatCount: 111),
    SuraDataModel(suraNameAR: "الكهف",
        suraNameEN: "Al-Kahf",
        suraNumber: 18,
        suraAyatCount: 110),
    SuraDataModel(suraNameAR: "مريم",
        suraNameEN: "Maryam",
        suraNumber: 19,
        suraAyatCount: 98),
    SuraDataModel(suraNameAR: "طه",
        suraNameEN: "Ta-Ha",
        suraNumber: 20,
        suraAyatCount: 135),
    SuraDataModel(suraNameAR: "الأنبياء",
        suraNameEN: "Al-Anbiya",
        suraNumber: 21,
        suraAyatCount: 112),
    SuraDataModel(suraNameAR: "الحج",
        suraNameEN: "Al-Hajj",
        suraNumber: 22,
        suraAyatCount: 78),
    SuraDataModel(suraNameAR: "المؤمنون",
        suraNameEN: "Al-Mu'minun",
        suraNumber: 23,
        suraAyatCount: 118),
    SuraDataModel(suraNameAR: "النّور",
        suraNameEN: "An-Nur",
        suraNumber: 24,
        suraAyatCount: 64),
    SuraDataModel(suraNameAR: "الفرقان",
        suraNameEN: "Al-Furqan",
        suraNumber: 25,
        suraAyatCount: 77),
    SuraDataModel(suraNameAR: "الشعراء",
        suraNameEN: "Ash-Shu'ara",
        suraNumber: 26,
        suraAyatCount: 227),
    SuraDataModel(suraNameAR: "النّمل",
        suraNameEN: "An-Naml",
        suraNumber: 27,
        suraAyatCount: 93),
    SuraDataModel(suraNameAR: "القصص",
        suraNameEN: "Al-Qasas",
        suraNumber: 28,
        suraAyatCount: 88),
    SuraDataModel(suraNameAR: "العنكبوت",
        suraNameEN: "Al-Ankabut",
        suraNumber: 29,
        suraAyatCount: 69),
    SuraDataModel(suraNameAR: "الرّوم",
        suraNameEN: "Ar-Rum",
        suraNumber: 30,
        suraAyatCount: 60),
    SuraDataModel(suraNameAR: "لقمان",
        suraNameEN: "Luqman",
        suraNumber: 31,
        suraAyatCount: 34),
    SuraDataModel(suraNameAR: "السجدة",
        suraNameEN: "As-Sajda",
        suraNumber: 32,
        suraAyatCount: 30),
    SuraDataModel(suraNameAR: "الأحزاب",
        suraNameEN: "Al-Ahzab",
        suraNumber: 33,
        suraAyatCount: 73),
    SuraDataModel(suraNameAR: "سبأ",
        suraNameEN: "Saba",
        suraNumber: 34,
        suraAyatCount: 54),
    SuraDataModel(suraNameAR: "فاطر",
        suraNameEN: "Fatir",
        suraNumber: 35,
        suraAyatCount: 45),
    SuraDataModel(suraNameAR: "يس",
        suraNameEN: "Ya-Sin",
        suraNumber: 36,
        suraAyatCount: 83),
    SuraDataModel(suraNameAR: "الصافات",
        suraNameEN: "As-Saffat",
        suraNumber: 37,
        suraAyatCount: 182),
    SuraDataModel(
        suraNameAR: "ص", suraNameEN: "Sad", suraNumber: 38, suraAyatCount: 88),
    SuraDataModel(suraNameAR: "الزمر",
        suraNameEN: "Az-Zumar",
        suraNumber: 39,
        suraAyatCount: 75),
    SuraDataModel(suraNameAR: "غافر",
        suraNameEN: "Ghafir",
        suraNumber: 40,
        suraAyatCount: 85),
    SuraDataModel(suraNameAR: "فصّلت",
        suraNameEN: "Fussilat",
        suraNumber: 41,
        suraAyatCount: 54),
    SuraDataModel(suraNameAR: "الشورى",
        suraNameEN: "Ash-Shura",
        suraNumber: 42,
        suraAyatCount: 53),
    SuraDataModel(suraNameAR: "الزخرف",
        suraNameEN: "Az-Zukhruf",
        suraNumber: 43,
        suraAyatCount: 89),
    SuraDataModel(suraNameAR: "الدّخان",
        suraNameEN: "Ad-Dukhan",
        suraNumber: 44,
        suraAyatCount: 59),
    SuraDataModel(suraNameAR: "الجاثية",
        suraNameEN: "Al-Jathiya",
        suraNumber: 45,
        suraAyatCount: 37),
    SuraDataModel(suraNameAR: "الأحقاف",
        suraNameEN: "Al-Ahqaf",
        suraNumber: 46,
        suraAyatCount: 35),
    SuraDataModel(suraNameAR: "محمد",
        suraNameEN: "Muhammad",
        suraNumber: 47,
        suraAyatCount: 38),
    SuraDataModel(suraNameAR: "الفتح",
        suraNameEN: "Al-Fath",
        suraNumber: 48,
        suraAyatCount: 29),
    SuraDataModel(suraNameAR: "الحجرات",
        suraNameEN: "Al-Hujurat",
        suraNumber: 49,
        suraAyatCount: 18),
    SuraDataModel(
        suraNameAR: "ق", suraNameEN: "Qaf", suraNumber: 50, suraAyatCount: 45),
    SuraDataModel(suraNameAR: "الذاريات",
        suraNameEN: "Adh-Dhariyat",
        suraNumber: 51,
        suraAyatCount: 60),
    SuraDataModel(suraNameAR: "الطور",
        suraNameEN: "At-Tur",
        suraNumber: 52,
        suraAyatCount: 49),
    SuraDataModel(suraNameAR: "النجم",
        suraNameEN: "An-Najm",
        suraNumber: 53,
        suraAyatCount: 62),
    SuraDataModel(suraNameAR: "القمر",
        suraNameEN: "Al-Qamar",
        suraNumber: 54,
        suraAyatCount: 55),
    SuraDataModel(suraNameAR: "الرحمن",
        suraNameEN: "Ar-Rahman",
        suraNumber: 55,
        suraAyatCount: 78),
    SuraDataModel(suraNameAR: "الواقعة",
        suraNameEN: "Al-Waqi'a",
        suraNumber: 56,
        suraAyatCount: 96),
    SuraDataModel(suraNameAR: "الحديد",
        suraNameEN: "Al-Hadid",
        suraNumber: 57,
        suraAyatCount: 29),
    SuraDataModel(suraNameAR: "المجادلة",
        suraNameEN: "Al-Mujadila",
        suraNumber: 58,
        suraAyatCount: 22),
    SuraDataModel(suraNameAR: "الحشر",
        suraNameEN: "Al-Hashr",
        suraNumber: 59,
        suraAyatCount: 24),
    SuraDataModel(suraNameAR: "الممتحنة",
        suraNameEN: "Al-Mumtahina",
        suraNumber: 60,
        suraAyatCount: 13),
    SuraDataModel(suraNameAR: "الصف",
        suraNameEN: "As-Saff",
        suraNumber: 61,
        suraAyatCount: 14),
    SuraDataModel(suraNameAR: "الجمعة",
        suraNameEN: "Al-Jumu'a",
        suraNumber: 62,
        suraAyatCount: 11),
    SuraDataModel(suraNameAR: "المنافقون",
        suraNameEN: "Al-Munafiqun",
        suraNumber: 63,
        suraAyatCount: 11),
    SuraDataModel(suraNameAR: "التغابن",
        suraNameEN: "At-Taghabun",
        suraNumber: 64,
        suraAyatCount: 18),
    SuraDataModel(suraNameAR: "الطلاق",
        suraNameEN: "At-Talaq",
        suraNumber: 65,
        suraAyatCount: 12),
    SuraDataModel(suraNameAR: "التحريم",
        suraNameEN: "At-Tahrim",
        suraNumber: 66,
        suraAyatCount: 12),
    SuraDataModel(suraNameAR: "الملك",
        suraNameEN: "Al-Mulk",
        suraNumber: 67,
        suraAyatCount: 30),
    SuraDataModel(suraNameAR: "القلم",
        suraNameEN: "Al-Qalam",
        suraNumber: 68,
        suraAyatCount: 52),
    SuraDataModel(suraNameAR: "الحاقة",
        suraNameEN: "Al-Haqqah",
        suraNumber: 69,
        suraAyatCount: 52),
    SuraDataModel(suraNameAR: "المعارج",
        suraNameEN: "Al-Ma'arij",
        suraNumber: 70,
        suraAyatCount: 44),
    SuraDataModel(suraNameAR: "نوح",
        suraNameEN: "Nuh",
        suraNumber: 71,
        suraAyatCount: 28),
    SuraDataModel(suraNameAR: "الجن",
        suraNameEN: "Al-Jinn",
        suraNumber: 72,
        suraAyatCount: 28),
    SuraDataModel(suraNameAR: "المزّمّل",
        suraNameEN: "Al-Muzzammil",
        suraNumber: 73,
        suraAyatCount: 20),
    SuraDataModel(suraNameAR: "المدّثر",
        suraNameEN: "Al-Muddathir",
        suraNumber: 74,
        suraAyatCount: 56),
    SuraDataModel(suraNameAR: "القيامة",
        suraNameEN: "Al-Qiyamah",
        suraNumber: 75,
        suraAyatCount: 40),
    SuraDataModel(suraNameAR: "الإنسان",
        suraNameEN: "Al-Insan",
        suraNumber: 76,
        suraAyatCount: 31),
    SuraDataModel(suraNameAR: "المرسلات",
        suraNameEN: "Al-Mursalat",
        suraNumber: 77,
        suraAyatCount: 50),
    SuraDataModel(suraNameAR: "النبأ",
        suraNameEN: "An-Naba'",
        suraNumber: 78,
        suraAyatCount: 40),
    SuraDataModel(suraNameAR: "النازعات",
        suraNameEN: "An-Nazi'at",
        suraNumber: 79,
        suraAyatCount: 46),
    SuraDataModel(suraNameAR: "عبس",
        suraNameEN: "Abasa",
        suraNumber: 80,
        suraAyatCount: 42),
    SuraDataModel(suraNameAR: "التكوير",
        suraNameEN: "At-Takwir",
        suraNumber: 81,
        suraAyatCount: 29),
    SuraDataModel(suraNameAR: "الإنفطار",
        suraNameEN: "Al-Infitar",
        suraNumber: 82,
        suraAyatCount: 19),
    SuraDataModel(suraNameAR: "المطفّفين",
        suraNameEN: "Al-Mutaffifin",
        suraNumber: 83,
        suraAyatCount: 36),
    SuraDataModel(suraNameAR: "الإنشقاق",
        suraNameEN: "Al-Inshiqaq",
        suraNumber: 84,
        suraAyatCount: 25),
    SuraDataModel(suraNameAR: "البروج",
        suraNameEN: "Al-Buruj",
        suraAyatCount: 22,
        suraNumber: 85),
    SuraDataModel(suraNameAR: "الطارق",
        suraNameEN: "At-Tariq",
        suraAyatCount: 17,
        suraNumber: 86),
    SuraDataModel(suraNameAR: "الأعلى",
        suraNameEN: "Al-A'la",
        suraAyatCount: 19,
        suraNumber: 87),
    SuraDataModel(suraNameAR: "الغاشية",
        suraNameEN: "Al-Ghashiyah",
        suraAyatCount: 26,
        suraNumber: 88),
    SuraDataModel(suraNameAR: "الفجر",
        suraNameEN: "Al-Fajr",
        suraAyatCount: 30,
        suraNumber: 89),
    SuraDataModel(suraNameAR: "البلد",
        suraNameEN: "Al-Balad",
        suraAyatCount: 20,
        suraNumber: 90),
    SuraDataModel(suraNameAR: "الشمس",
        suraNameEN: "Ash-Shams",
        suraAyatCount: 15,
        suraNumber: 91),
    SuraDataModel(suraNameAR: "الليل",
        suraNameEN: "Al-Lail",
        suraAyatCount: 21,
        suraNumber: 92),
    SuraDataModel(suraNameAR: "الضحى",
        suraNameEN: "Ad-Duha",
        suraAyatCount: 11,
        suraNumber: 93),
    SuraDataModel(suraNameAR: "الشرح",
        suraNameEN: "Ash-Sharh",
        suraAyatCount: 8,
        suraNumber: 94),
    SuraDataModel(suraNameAR: "التين",
        suraNameEN: "At-Tin",
        suraAyatCount: 8,
        suraNumber: 95),
    SuraDataModel(suraNameAR: "العلق",
        suraNameEN: "Al-Alaq",
        suraAyatCount: 19,
        suraNumber: 96),
    SuraDataModel(suraNameAR: "القدر",
        suraNameEN: "Al-Qadr",
        suraAyatCount: 5,
        suraNumber: 97),
    SuraDataModel(suraNameAR: "البينة",
        suraNameEN: "Al-Bayyina",
        suraAyatCount: 8,
        suraNumber: 98),
    SuraDataModel(suraNameAR: "الزلزلة",
        suraNameEN: "Az-Zalzalah",
        suraAyatCount: 8,
        suraNumber: 99),
    SuraDataModel(suraNameAR: "العاديات",
        suraNameEN: "Al-Adiyat",
        suraAyatCount: 11,
        suraNumber: 100),
    SuraDataModel(suraNameAR: "القارعة",
        suraNameEN: "Al-Qari'a",
        suraAyatCount: 11,
        suraNumber: 101),
    SuraDataModel(suraNameAR: "التكاثر",
        suraNameEN: "At-Takathur",
        suraAyatCount: 8,
        suraNumber: 102),
    SuraDataModel(suraNameAR: "العصر",
        suraNameEN: "Al-Asr",
        suraAyatCount: 3,
        suraNumber: 103),
    SuraDataModel(suraNameAR: "الهمزة",
        suraNameEN: "Al-Humazah",
        suraAyatCount: 9,
        suraNumber: 104),
    SuraDataModel(suraNameAR: "الفيل",
        suraNameEN: "Al-Fil",
        suraAyatCount: 5,
        suraNumber: 105),
    SuraDataModel(suraNameAR: "قريش",
        suraNameEN: "Quraysh",
        suraAyatCount: 4,
        suraNumber: 106),
    SuraDataModel(suraNameAR: "الماعون",
        suraNameEN: "Al-Ma'un",
        suraAyatCount: 7,
        suraNumber: 107),
    SuraDataModel(suraNameAR: "الكوثر",
        suraNameEN: "Al-Kawthar",
        suraAyatCount: 3,
        suraNumber: 108),
    SuraDataModel(suraNameAR: "الكافرون",
        suraNameEN: "Al-Kafirun",
        suraAyatCount: 6,
        suraNumber: 109),
    SuraDataModel(suraNameAR: "النصر",
        suraNameEN: "An-Nasr",
        suraAyatCount: 3,
        suraNumber: 110),
    SuraDataModel(suraNameAR: "المسد",
        suraNameEN: "Al-Masad",
        suraAyatCount: 5,
        suraNumber: 111),
    SuraDataModel(suraNameAR: "الإخلاص",
        suraNameEN: "Al-Ikhlas",
        suraAyatCount: 4,
        suraNumber: 112),
    SuraDataModel(suraNameAR: "الفلق",
        suraNameEN: "Al-Falaq",
        suraAyatCount: 5,
        suraNumber: 113),
    SuraDataModel(suraNameAR: "الناس",
        suraNameEN: "An-Nas",
        suraAyatCount: 6,
        suraNumber: 114),
  ];

  List<SuraDataModel> recentReadSuras = [
    SuraDataModel(suraNameAR: "الأنبياء",
        suraNameEN: "Al-Anbiya",
        suraNumber: 21,
        suraAyatCount: 112),
    SuraDataModel(suraNameAR: "الفاتحه",
        suraNameEN: "Al-Fatiha",
        suraNumber: 1,
        suraAyatCount: 7),
    SuraDataModel(suraNameAR: "البقرة",
        suraNameEN: "Al-Baqarah",
        suraNumber: 2,
        suraAyatCount: 286),
    SuraDataModel(suraNameAR: "آل عمران",
        suraNameEN: "Aal-E-Imran",
        suraNumber: 3,
        suraAyatCount: 200),
  ];

  @override
  Widget build(BuildContext context) {
    var theme = Theme.of(context);
    return Container(
      height: double.infinity,
      width: double.infinity,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: AssetImage(AppAssets.quranBackground),
          fit: BoxFit.cover,
        ),
      ),
      child: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Image.asset(AppAssets.islamiLogo),
            Padding(
              padding: const EdgeInsets.symmetric(
                  horizontal: 20.0, vertical: 10),
              child: TextField(
                cursorColor: ColorPalette.primaryColor,
                decoration: InputDecoration(
                  hintText: "Sura Name",
                  hintStyle: theme.textTheme.bodyLarge,
                  prefixIcon: Padding(
                    padding: const EdgeInsets.all(10.0),
                    child: ImageIcon(
                      AssetImage(AppAssets.quranIcon),
                      color: ColorPalette.primaryColor,
                    ),
                  ),

                  focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(10),
                    borderSide: BorderSide(color: ColorPalette.primaryColor),
                  ),
                  enabledBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(10),
                    borderSide: BorderSide(color: ColorPalette.primaryColor),
                  ),
                ),
              ),
            ),
            Padding(
              padding: const EdgeInsets.symmetric(
                horizontal: 20.0,
                vertical: 10.0,
              ),
              child: Align(
                alignment: Alignment.centerLeft,
                child: Text("Most Recently", style: theme.textTheme.bodyLarge),
              ),

            ),
            SizedBox(
              height: 160,
              child: ListView.separated(
                scrollDirection: Axis.horizontal,
                padding: EdgeInsets.symmetric(horizontal: 20.0),
                itemBuilder: (context, index) {
                  return RecentlyCardWidget(
                    suraDataModel: recentReadSuras[index],
                  );
                },
                separatorBuilder: (context, index) {
                  return SizedBox(width: 10.0,);
                },
                itemCount: recentReadSuras.length,
              ),
            ),
            Padding(
              padding: const EdgeInsets.symmetric(
                horizontal: 20.0,
                vertical: 10.0,
              ),
              child: Align(
                alignment: Alignment.centerLeft,
                child: Text("Suras List", style: theme.textTheme.bodyLarge),
              ),

            ),
            ListView.separated(
              shrinkWrap: true,
              physics: NeverScrollableScrollPhysics(),
              padding: EdgeInsets.zero,
              itemBuilder: (context, index) {
                return QuranCardWidgett(suraDataModel: allSuras [index]);
              },
              separatorBuilder: (context, index) {
                return Divider(
                  color: Colors.white,
                  thickness: 2,
                  indent: 60.0,
                  endIndent: 60.0,

                );
              },
              itemCount: allSuras.length,
            ),
          ],
        ),
      ),
    );
  }
}